spring:
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client: DEBUG
      hibernate: DEBUG


kokocast:
  properties:
    real-time-server-url: http://localhost:8002