spring:
  profiles:
    include: secret
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client: DEBUG
      hibernate: DEBUG


kokocast:
  properties:
    real-time-server-url: http://localhost:8002