spring:
  profiles:
    include: secret
server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO


kokocast:
  properties:
    real-time-server-url: http://localhost:8002